// Generated by tools/voice-timing.mjs — do not edit by hand.
export const VOICE = {
  "generator": "elevenlabs",
  "model": "eleven_turbo_v2_5",
  "source": "/home/tunm17421/Claude-Design/tts-elevenlabs/out/n2-00-gioi-thieu-ngay-2/voice.cues.json",
  "audioSha256": "dc335d9f6339de03ec392e25840de210fe82256e4a59376bca5a03d627d35c77",
  "durationInFrames": 3584,
  "cues": [
    {
      "n": 1,
      "durationInFrames": 229,
      "speechFrames": 199,
      "text": "Nếu được nhờ làm một trợ lý trí tuệ nhân tạo, bạn sẽ bắt đầu bằng việc chọn công cụ hay tìm hiểu người dùng đang gặp khó khăn gì?"
    },
    {
      "n": 2,
      "durationInFrames": 177,
      "speechFrames": 147,
      "text": "Chào bạn, ngày hai giúp chúng ta làm rõ vấn đề trước khi quyết định dùng công nghệ để giải quyết."
    },
    {
      "n": 3,
      "durationInFrames": 211,
      "speechFrames": 181,
      "text": "Bạn sẽ học cách xác định việc cần cải thiện, chọn cách giải quyết và kiểm tra xem đã đủ điều kiện để bắt đầu làm hay chưa."
    },
    {
      "n": 4,
      "durationInFrames": 194,
      "speechFrames": 164,
      "text": "Đầu tiên, bạn sẽ học cách tìm khó khăn thật sự đằng sau một đề nghị như làm trợ lý hỗ trợ học viên."
    },
    {
      "n": 5,
      "durationInFrames": 216,
      "speechFrames": 186,
      "text": "Qua ví dụ một học viên tìm hướng dẫn nộp bài, bạn sẽ quan sát họ tìm ở đâu và hỏi bước nào khiến họ mất thời gian."
    },
    {
      "n": 6,
      "durationInFrames": 219,
      "speechFrames": 189,
      "text": "Phần hai giúp bạn viết rõ ai đang gặp khó, họ vướng ở bước nào và việc đó gây chậm trễ hoặc sai sót gì."
    },
    {
      "n": 7,
      "durationInFrames": 226,
      "speechFrames": 196,
      "text": "Bạn sẽ ghi lại hiện nay học viên mất bao lâu để tìm đúng hướng dẫn, chọn thời gian muốn rút ngắn, rồi đo lại sau khi cải thiện."
    },
    {
      "n": 8,
      "durationInFrames": 212,
      "speechFrames": 182,
      "text": "Phần ba đặt câu hỏi: trí tuệ nhân tạo, hay AI, có thực sự giúp ích cho công việc ấy hay không."
    },
    {
      "n": 9,
      "durationInFrames": 183,
      "speechFrames": 153,
      "text": "Bạn sẽ cân nhắc những việc có thể giao AI làm thay và những việc AI nên hỗ trợ để con người quyết định."
    },
    {
      "n": 10,
      "durationInFrames": 303,
      "speechFrames": 273,
      "text": "Ở phần bốn, bạn sẽ so sánh hai cách tổ chức công việc: con người đặt sẵn quy tắc và các bước xử lý, hoặc để AI chọn bước tiếp theo dựa trên kết quả vừa nhận được."
    },
    {
      "n": 11,
      "durationInFrames": 182,
      "speechFrames": 152,
      "text": "Mục đích là chọn cách đủ giải quyết công việc, đồng thời cân nhắc chi phí, thời gian chờ và rủi ro."
    },
    {
      "n": 12,
      "durationInFrames": 196,
      "speechFrames": 166,
      "text": "Phần năm giúp bạn xác định thế nào là kết quả đạt yêu cầu và cần làm gì khi hệ thống AI cho ra kết quả sai."
    },
    {
      "n": 13,
      "durationInFrames": 266,
      "speechFrames": 236,
      "text": "Bạn sẽ xem hai lỗi thường gặp: hệ thống AI báo nhầm rằng một người cần giúp dù họ không gặp khó, hoặc bỏ sót người thật sự đang cần hỗ trợ."
    },
    {
      "n": 14,
      "durationInFrames": 202,
      "speechFrames": 172,
      "text": "Phần sáu giúp bạn hoàn chỉnh bản mô tả vấn đề, cách giải quyết dự kiến và những điều phải kiểm tra trước khi bắt đầu làm."
    },
    {
      "n": 15,
      "durationInFrames": 228,
      "speechFrames": 198,
      "text": "Bạn sẽ cân nhắc đi tiếp, chuẩn bị thêm hoặc dừng đề xuất, dựa vào lợi ích dự kiến và khả năng kiểm soát rủi ro."
    },
    {
      "n": 16,
      "durationInFrames": 340,
      "speechFrames": 310,
      "text": "Sau hôm nay, bạn sẽ biết bài toán nào thật sự cần AI, AI nên làm thay hay hỗ trợ con người, và khi nào nên làm tiếp, chuẩn bị thêm hoặc dừng ý tưởng sản phẩm đó."
    }
  ]
};
