// Generated by tools/voice-timing.mjs — do not edit by hand.
export const VOICE = {
  "generator": "elevenlabs",
  "model": "eleven_turbo_v2_5",
  "source": "/home/tunm17421/Claude-Design/tts-elevenlabs/out/d2-01-lab-v2-turbo/voice.cues.json",
  "audioSha256": "bb1589dad26cce8ec6676579b884df71e6cb61867fc6de7c4c188f3e457d82e8",
  "durationInFrames": 13400,
  "cues": [
    {
      "n": 1,
      "durationInFrames": 244,
      "speechFrames": 220,
      "text": "Trước khi các bạn chọn cách xây một giải pháp, có một câu hỏi cần được giữ ở giữa cả ngày học: mình đã chắc là đang giải đúng bài toán chưa?"
    },
    {
      "n": 2,
      "durationInFrames": 90,
      "speechFrames": 0,
      "text": ""
    },
    {
      "n": 3,
      "durationInFrames": 161,
      "speechFrames": 113,
      "text": "Không phải cứ nhìn thấy một giải pháp là đã nhìn thấy nhu cầu cần giải quyết."
    },
    {
      "n": 4,
      "durationInFrames": 168,
      "speechFrames": 120,
      "text": "Cũng không phải cứ có thể đưa AI vào là bài toán đó thật sự cần AI."
    },
    {
      "n": 5,
      "durationInFrames": 342,
      "speechFrames": 282,
      "text": "Vậy trước khi nói đến cấp độ giải pháp, trước khi đề xuất công nghệ, chúng ta cần làm rõ điều gì đang xảy ra, điều gì cần thay đổi, và quyết định nào đang được đặt ra."
    },
    {
      "n": 6,
      "durationInFrames": 223,
      "speechFrames": 175,
      "text": "Sau ngày này, các bạn sẽ phân biệt được bài toán với giải pháp, và biết đặt câu hỏi làm rõ trước khi đề xuất công nghệ."
    },
    {
      "n": 7,
      "durationInFrames": 426,
      "speechFrames": 378,
      "text": "Các bạn sẽ định lượng hóa được một điểm đau bằng hiện trạng, mục tiêu và cách đo, để điểm đau không chỉ được mô tả chung chung mà có thể được nhìn nhận rõ hơn qua những gì đang có, điều cần đạt tới và cách kiểm chứng."
    },
    {
      "n": 8,
      "durationInFrames": 442,
      "speechFrames": 394,
      "text": "Các bạn cũng sẽ áp dụng được ba bước để xác định AI có đáng làm hay không, việc nào nên để AI làm thay con người và việc nào chỉ nên để AI hỗ trợ con người, và giải pháp nên dừng ở cấp độ đơn giản nhất mà vẫn đủ giải quyết bài toán."
    },
    {
      "n": 9,
      "durationInFrames": 231,
      "speechFrames": 171,
      "text": "Sau đó, các bạn sẽ viết được tiêu chí thành công có thể hành động, đồng thời biết ứng xử khi AI sai."
    },
    {
      "n": 10,
      "durationInFrames": 288,
      "speechFrames": 240,
      "text": "Mục tiêu không dừng ở việc gọi tên một giải pháp, mà là làm rõ giải pháp đó cần đạt điều gì và cần được nhìn nhận ra sao khi kết quả không đúng."
    },
    {
      "n": 11,
      "durationInFrames": 316,
      "speechFrames": 268,
      "text": "Cuối ngày, các bạn sẽ hoàn thành được một bản mô tả bài toán đủ chín mục để quyết định nên triển khai, tạm hoãn hay dừng lại, trong buổi thực hành."
    },
    {
      "n": 12,
      "durationInFrames": 478,
      "speechFrames": 418,
      "text": "Nghĩa là các bạn có thể đi từ việc nhận diện bài toán, làm rõ điểm đau và khả năng cần AI, đến việc xác định cấp độ giải pháp, tiêu chí thành công, cách ứng xử khi AI thất bại, rồi đưa bài toán về một dạng đủ rõ để quyết định triển khai."
    },
    {
      "n": 13,
      "durationInFrames": 221,
      "speechFrames": 173,
      "text": "Ngày học này đi theo một lập trường rất rõ: chúng ta sẽ đặt câu hỏi xuyên suốt, thay vì vội đi tìm giải pháp."
    },
    {
      "n": 14,
      "durationInFrames": 373,
      "speechFrames": 325,
      "text": "Bốn câu hỏi trọng tâm sẽ lần lượt dẫn đường cho cả ngày: bài toán có thật sự cần AI không, giải pháp nên ở cấp độ nào, bản mô tả bài toán đã đủ rõ chưa, và khi nào nên quyết định triển khai."
    },
    {
      "n": 15,
      "durationInFrames": 240,
      "speechFrames": 192,
      "text": "Ngày học không đòi hỏi kiến thức kỹ thuật sâu; điều cần có là khả năng đặt câu hỏi và quan sát một quy trình thật."
    },
    {
      "n": 16,
      "durationInFrames": 235,
      "speechFrames": 175,
      "text": "Vì vậy, cách tiếp cận của chúng ta là nhìn bài toán trước, làm rõ trước, rồi mới nói đến công nghệ và quyết định."
    },
    {
      "n": 17,
      "durationInFrames": 229,
      "speechFrames": 187,
      "text": "Bây giờ, mình bắt đầu từ điểm dễ bị bỏ qua nhất: khi giải pháp xuất hiện trước khi bài toán được nhìn thấy rõ."
    },
    {
      "n": 18,
      "durationInFrames": 185,
      "speechFrames": 125,
      "text": "Chúng ta vào Module 1 · Nhìn thấy giải pháp trước khi thấy bài toán."
    },
    {
      "n": 19,
      "durationInFrames": 162,
      "speechFrames": 120,
      "text": "Các bạn chắc đã gặp một yêu cầu rất quen: xây một chatbot AI."
    },
    {
      "n": 20,
      "durationInFrames": 196,
      "speechFrames": 154,
      "text": "Nghe qua, yêu cầu này giống như đã nói rõ việc cần làm, vì nó đã gọi tên một hình hài giải pháp."
    },
    {
      "n": 21,
      "durationInFrames": 237,
      "speechFrames": 195,
      "text": "Nhưng nếu dừng ở đó, chúng ta vẫn chưa biết ai sẽ dùng, họ đang vướng ở đâu, và chatbot cần tham gia vào công việc nào."
    },
    {
      "n": 22,
      "durationInFrames": 248,
      "speechFrames": 206,
      "text": "Điều này đáng bận tâm vì cùng một cái tên chatbot có thể dẫn tới những quy trình, chỉ số và rủi ro rất khác nhau."
    },
    {
      "n": 23,
      "durationInFrames": 319,
      "speechFrames": 259,
      "text": "Trong module này, mình sẽ tập cho các bạn trả lời ba câu hỏi đó trước: ai sẽ dùng, họ đang vướng ở đâu, và chatbot cần tham gia vào công việc nào."
    },
    {
      "n": 24,
      "durationInFrames": 248,
      "speechFrames": 206,
      "text": "Bây giờ mình dùng một ví dụ xuyên suốt: cùng một yêu cầu xây chatbot AI, nhưng đặt nó vào hai nhóm người dùng khác nhau."
    },
    {
      "n": 25,
      "durationInFrames": 164,
      "speechFrames": 122,
      "text": "Ở vế thứ nhất là khách hàng bên ngoài; ở vế thứ hai là nhân sự nội bộ."
    },
    {
      "n": 26,
      "durationInFrames": 190,
      "speechFrames": 166,
      "text": "Các bạn thử dự đoán trước: nếu chỉ đổi đối tượng phục vụ, liệu công việc phía sau có còn giống nhau không?"
    },
    {
      "n": 27,
      "durationInFrames": 90,
      "speechFrames": 0,
      "text": ""
    },
    {
      "n": 28,
      "durationInFrames": 394,
      "speechFrames": 346,
      "text": "Khi phục vụ khách hàng bên ngoài, quy trình có thể bắt đầu từ một câu hỏi của khách về sản phẩm hoặc chính sách, rồi đi tới việc giải đáp, tư vấn mua hàng, chăm sóc sau mua, hoặc hỗ trợ bán thêm và bán chéo."
    },
    {
      "n": 29,
      "durationInFrames": 465,
      "speechFrames": 417,
      "text": "Khi hỗ trợ nhân sự nội bộ, cùng yêu cầu chatbot lại có thể bắt đầu từ một yêu cầu hỗ trợ, rồi cần phân loại yêu cầu, tra cứu thông tin nghiệp vụ nhanh, đề xuất nháp phản hồi để con người phê duyệt, hoặc chuyển câu hỏi phức tạp và rủi ro cao cho nhân sự hỗ trợ."
    },
    {
      "n": 30,
      "durationInFrames": 281,
      "speechFrames": 233,
      "text": "Ở đây, workflow, tức là chuỗi các bước đang diễn ra để xử lý một việc, giúp các bạn nhìn thấy chatbot sẽ đứng ở đâu trong công việc thực tế."
    },
    {
      "n": 31,
      "durationInFrames": 358,
      "speechFrames": 310,
      "text": "Workflow của khách hàng bên ngoài xoay quanh việc giải đáp và hỗ trợ mua hàng; workflow của nội bộ lại xoay quanh yêu cầu hỗ trợ, tra cứu, soạn nháp và chuyển tiếp."
    },
    {
      "n": 32,
      "durationInFrames": 240,
      "speechFrames": 180,
      "text": "Vì vậy, đừng coi chatbot là toàn bộ bài toán; nó chỉ là một khả năng được đặt vào một workflow cụ thể."
    },
    {
      "n": 33,
      "durationInFrames": 106,
      "speechFrames": 58,
      "text": "Mình đi sâu thêm một bước với ví dụ này."
    },
    {
      "n": 34,
      "durationInFrames": 290,
      "speechFrames": 242,
      "text": "Tình huống thứ nhất là một chatbot phục vụ khách hàng: nó gặp câu hỏi thường gặp về sản phẩm và chính sách, sau đó hỗ trợ tư vấn mua hàng."
    },
    {
      "n": 35,
      "durationInFrames": 248,
      "speechFrames": 200,
      "text": "Tình huống thứ hai là chatbot phục vụ nội bộ: nó tiếp nhận yêu cầu hỗ trợ, tra cứu thông tin nghiệp vụ và chuẩn bị nháp phản hồi."
    },
    {
      "n": 36,
      "durationInFrames": 292,
      "speechFrames": 244,
      "text": "Tình huống thứ ba là khi câu hỏi phức tạp hoặc rủi ro cao xuất hiện: việc xử lý được chuyển cho nhân sự hỗ trợ, thay vì để chatbot tự đi tiếp."
    },
    {
      "n": 37,
      "durationInFrames": 158,
      "speechFrames": 116,
      "text": "Các bạn thấy đấy, đối tượng khác nhau không chỉ đổi giao diện hay cách gọi tên."
    },
    {
      "n": 38,
      "durationInFrames": 206,
      "speechFrames": 164,
      "text": "Nó đổi cả công việc cần xử lý, bước nào được tự động hỗ trợ, và lúc nào con người phải tham gia."
    },
    {
      "n": 39,
      "durationInFrames": 252,
      "speechFrames": 192,
      "text": "Vì thế, cùng một yêu cầu chatbot AI nhưng bên ngoài và bên trong không thể mặc nhiên dùng chung một cách mô tả bài toán."
    },
    {
      "n": 40,
      "durationInFrames": 129,
      "speechFrames": 81,
      "text": "Đến đây, mình muốn dừng lại ở chỗ các bạn dễ nhầm nhất."
    },
    {
      "n": 41,
      "durationInFrames": 164,
      "speechFrames": 116,
      "text": "Nếu nói “hãy làm chatbot”, các bạn có thể bắt đầu nghĩ ngay tới công nghệ."
    },
    {
      "n": 42,
      "durationInFrames": 392,
      "speechFrames": 344,
      "text": "Nhưng hãy đi ngược lại từng bước: trước hết hỏi người dùng đang mắc ở công đoạn nào; tiếp theo xem quy trình hiện tại đang diễn ra ra sao; rồi xác định ai đang bị quá tải và điểm vướng xuất hiện lặp lại ở đâu."
    },
    {
      "n": 43,
      "durationInFrames": 296,
      "speechFrames": 248,
      "text": "pain point, tức là điểm đau cụ thể nơi người dùng gặp khó khăn, phàn nàn hoặc bị tắc nghẽn, là thứ cần được nhận diện trước khi đề xuất giải pháp."
    },
    {
      "n": 44,
      "durationInFrames": 217,
      "speechFrames": 157,
      "text": "Khi chưa hiểu pain point, mình chưa có căn cứ để biết chatbot có đang giải quyết đúng việc hay không."
    },
    {
      "n": 45,
      "durationInFrames": 358,
      "speechFrames": 310,
      "text": "Các bạn cũng cần một metric, tức là chỉ số dùng để theo dõi và đánh giá kết quả của việc cải tiến, vì slide nhấn mạnh rằng các đối tượng khác nhau dẫn tới các chỉ số khác nhau."
    },
    {
      "n": 46,
      "durationInFrames": 269,
      "speechFrames": 221,
      "text": "Ở đây mình không tự gán tên hay giá trị cụ thể cho chỉ số; điều cần nhớ là không được dùng một bộ đo mặc định cho hai bài toán khác nhau."
    },
    {
      "n": 47,
      "durationInFrames": 179,
      "speechFrames": 137,
      "text": "Đó là lý do bắt đầu từ giải pháp thay vì điểm đau là dấu hiệu bài toán chưa sẵn sàng."
    },
    {
      "n": 48,
      "durationInFrames": 362,
      "speechFrames": 320,
      "text": "Những dấu hiệu khác cũng cần cảnh giác là chưa làm rõ quy trình vận hành, chưa có căn cứ đánh giá hiệu quả, hoặc chưa xác định ranh giới khi AI sai và thời điểm con người cần phê duyệt."
    },
    {
      "n": 49,
      "durationInFrames": 278,
      "speechFrames": 218,
      "text": "Khi gặp các dấu hiệu này, mình quay lại làm rõ Problem Statement, tức phần mô tả bài toán cần giải quyết, trước khi chọn công nghệ."
    },
    {
      "n": 50,
      "durationInFrames": 433,
      "speechFrames": 391,
      "text": "Các bạn hãy giữ lại mạch suy nghĩ này: yêu cầu chatbot chỉ cho chúng ta biết hình hài giải pháp; đối tượng phục vụ và pain point mới giúp làm rõ bài toán; workflow cho thấy công việc thực tế; còn metric giúp theo dõi kết quả."
    },
    {
      "n": 51,
      "durationInFrames": 287,
      "speechFrames": 227,
      "text": "Sang “Double Diamond: tìm đúng vấn đề trước khi tìm đúng giải pháp”, mình sẽ nối tiếp bằng cách tìm và định hình đúng vấn đề trước khi lựa chọn giải pháp."
    }
  ]
};
