apiVersion: 1
datasources:
  - name: Video Telemetry Postgres
    type: postgres
    access: proxy
    url: postgres:5432
    database: telemetry
    user: telemetry
    jsonData:
      sslmode: disable
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    isDefault: true
