// Generated by tools/voice-timing.mjs — do not edit by hand.
export const VOICE = {
  "generator": "elevenlabs",
  "model": "eleven_turbo_v2_5",
  "source": "voice/out/mau-huong-dan/voice.cues.json",
  "audioSha256": "9f38bacc2541b95f2bbd8353cd97701a4b542bd85450c9031f51c308d84333f1",
  "durationInFrames": 1133,
  "cues": [
    {
      "n": 1,
      "durationInFrames": 124,
      "speechFrames": 94,
      "text": "Xin chào, mình là Griffin, linh vật của VinUni.",
      "ttsText": "Xin chào, mình là Griffin, linh vật của VinUni.",
      "words": [[0,0],[4,5],[10,26],[15,31],[18,35],[27,62],[32,68],[36,73],[40,78]],
      "speaker": "Griffin",
      "avatar": "https://pub-75f38a18d7494e158433fd71f020ea01.r2.dev/mascot/griffin/face-happy.42579a9d4a.png?v=42579a9d4ac0",
      "side": "left",
      "tone": "accent"
    },
    {
      "n": 2,
      "durationInFrames": 139,
      "speechFrames": 109,
      "text": "Hôm nay mình kể bạn nghe một kịch bản trở thành video bài giảng như thế nào.",
      "ttsText": "Hôm nay mình kể bạn nghe một kịch bản trở thành video bài giảng như thế nào.",
      "words": [[0,0],[4,6],[8,10],[13,15],[16,23],[20,28],[25,35],[29,41],[34,47],[38,53],[42,58],[48,65],[54,76],[58,83],[64,90],[68,94],[72,98]],
      "speaker": "Griffin",
      "avatar": "https://pub-75f38a18d7494e158433fd71f020ea01.r2.dev/mascot/griffin/face-happy.42579a9d4a.png?v=42579a9d4ac0",
      "side": "left",
      "tone": "accent"
    },
    {
      "n": 3,
      "durationInFrames": 132,
      "speechFrames": 102,
      "text": "Đầu tiên, bạn chọn style và thả kịch bản vào Studio.",
      "ttsText": "Đầu tiên, bạn chọn style và thả kịch bản vào Studio.",
      "words": [[0,0],[4,6],[10,24],[14,29],[19,35],[25,47],[28,50],[32,55],[37,61],[41,68],[45,72]],
      "speaker": "Griffin",
      "avatar": "https://pub-75f38a18d7494e158433fd71f020ea01.r2.dev/mascot/griffin/face-happy.42579a9d4a.png?v=42579a9d4ac0",
      "side": "left",
      "tone": "accent"
    },
    {
      "n": 4,
      "durationInFrames": 159,
      "speechFrames": 129,
      "text": "Sau đó, agent cắt kịch bản thành từng câu và giữ nguyên văn từng chữ.",
      "ttsText": "Sau đó, agent cắt kịch bản thành từng câu và giữ nguyên văn từng chữ.",
      "words": [[0,0],[4,7],[8,26],[14,38],[18,44],[23,49],[27,55],[33,62],[38,69],[42,76],[45,80],[49,83],[56,90],[60,95],[65,101]],
      "speaker": "Griffin",
      "avatar": "https://pub-75f38a18d7494e158433fd71f020ea01.r2.dev/mascot/griffin/face-happy.42579a9d4a.png?v=42579a9d4ac0",
      "side": "left",
      "tone": "accent"
    },
    {
      "n": 5,
      "durationInFrames": 147,
      "speechFrames": 117,
      "text": "Giọng đọc được thu trước, rồi mỗi cảnh được dựng đúng theo độ dài của giọng thật.",
      "ttsText": "Giọng đọc được thu trước, rồi mỗi cảnh được dựng đúng theo độ dài của giọng thật.",
      "words": [[0,0],[6,7],[10,14],[15,18],[19,24],[26,43],[30,50],[34,55],[39,61],[44,68],[49,74],[54,80],[59,86],[62,91],[66,99],[70,104],[76,110]],
      "speaker": "Griffin",
      "avatar": "https://pub-75f38a18d7494e158433fd71f020ea01.r2.dev/mascot/griffin/face-happy.42579a9d4a.png?v=42579a9d4ac0",
      "side": "left",
      "tone": "accent"
    },
    {
      "n": 6,
      "durationInFrames": 164,
      "speechFrames": 134,
      "text": "Cuối cùng, Studio ghép hình, giọng và nhạc nền thành một tệp video.",
      "ttsText": "Cuối cùng, Studio ghép hình, giọng và nhạc nền thành một tệp video.",
      "words": [[0,0],[5,6],[11,22],[18,39],[23,45],[29,62],[35,70],[38,73],[43,80],[47,86],[53,92],[57,97],[61,102]],
      "speaker": "Griffin",
      "avatar": "https://pub-75f38a18d7494e158433fd71f020ea01.r2.dev/mascot/griffin/face-happy.42579a9d4a.png?v=42579a9d4ac0",
      "side": "left",
      "tone": "accent"
    },
    {
      "n": 7,
      "durationInFrames": 189,
      "speechFrames": 159,
      "text": "Xong mỗi bước, bạn duyệt rồi mới đi tiếp, nên không có gì chạy ngoài ý muốn.",
      "ttsText": "Xong mỗi bước, bạn duyệt rồi mới đi tiếp, nên không có gì chạy ngoài ý muốn.",
      "words": [[0,0],[5,9],[9,17],[15,36],[19,45],[25,55],[29,59],[33,63],[36,68],[42,90],[46,97],[52,103],[55,108],[58,114],[63,121],[69,127],[71,132]],
      "speaker": "Griffin",
      "avatar": "https://pub-75f38a18d7494e158433fd71f020ea01.r2.dev/mascot/griffin/face-happy.42579a9d4a.png?v=42579a9d4ac0",
      "side": "left",
      "tone": "accent"
    },
    {
      "n": 8,
      "durationInFrames": 79,
      "speechFrames": 49,
      "text": "Giờ thì đến lượt bạn thử rồi đó!",
      "ttsText": "Giờ thì đến lượt bạn thử rồi đó!",
      "words": [[0,0],[4,7],[8,11],[12,16],[17,22],[21,27],[25,33],[29,38]],
      "speaker": "Griffin",
      "avatar": "https://pub-75f38a18d7494e158433fd71f020ea01.r2.dev/mascot/griffin/face-happy.42579a9d4a.png?v=42579a9d4ac0",
      "side": "left",
      "tone": "accent"
    }
  ]
};
