// Generated by tools/voice-timing.mjs — do not edit by hand.
export const VOICE = {
  "generator": "elevenlabs",
  "model": "eleven_turbo_v2_5",
  "source": "voice/out/mau-huong-dan/voice.cues.json",
  "audioSha256": "6babe24dbea04e9341236341223529e69af50448501e428f3ad2285606757b5d",
  "durationInFrames": 1139,
  "cues": [
    {
      "n": 1,
      "durationInFrames": 130,
      "speechFrames": 100,
      "text": "Xin chào, mình là Griffin, linh vật của VinUni.",
      "ttsText": "Xin chào, mình là Gờ-ríp-phin, linh vật của Vin Uni.",
      "words": [[0,0],[4,7],[10,25],[15,31],[18,35],[31,62],[36,69],[40,75],[44,80],[48,88]],
      "speaker": "Griffin",
      "avatar": "https://pub-75f38a18d7494e158433fd71f020ea01.r2.dev/mascot/griffin/face-happy.42579a9d4a.png?v=42579a9d4ac0",
      "side": "left",
      "tone": "accent"
    },
    {
      "n": 2,
      "durationInFrames": 131,
      "speechFrames": 101,
      "text": "Hôm nay mình kể bạn nghe một kịch bản trở thành video bài giảng như thế nào.",
      "ttsText": "Hôm nay mình kể bạn nghe một kịch bản trở thành video bài giảng như thế nào.",
      "words": [[0,0],[4,6],[8,10],[13,15],[16,22],[20,29],[25,35],[29,40],[34,46],[38,52],[42,56],[48,61],[54,70],[58,75],[64,82],[68,86],[72,90]],
      "speaker": "Griffin",
      "avatar": "https://pub-75f38a18d7494e158433fd71f020ea01.r2.dev/mascot/griffin/face-happy.42579a9d4a.png?v=42579a9d4ac0",
      "side": "left",
      "tone": "accent"
    },
    {
      "n": 3,
      "durationInFrames": 138,
      "speechFrames": 108,
      "text": "Đầu tiên, bạn chọn style và thả kịch bản vào Studio.",
      "ttsText": "Đầu tiên, bạn chọn xờ-tai và thả kịch bản vào xờ-tiu-đi-ô.",
      "words": [[0,0],[4,7],[10,26],[14,32],[19,38],[26,53],[29,57],[33,62],[38,68],[42,75],[46,79]],
      "speaker": "Griffin",
      "avatar": "https://pub-75f38a18d7494e158433fd71f020ea01.r2.dev/mascot/griffin/face-happy.42579a9d4a.png?v=42579a9d4ac0",
      "side": "left",
      "tone": "accent"
    },
    {
      "n": 4,
      "durationInFrames": 139,
      "speechFrames": 109,
      "text": "Sau đó, agent cắt kịch bản thành từng câu và giữ nguyên văn từng chữ.",
      "ttsText": "Sau đó, ây-giần cắt kịch bản thành từng câu và giữ nguyên văn từng chữ.",
      "words": [[0,0],[4,7],[8,26],[16,38],[20,42],[25,48],[29,55],[35,60],[40,66],[44,73],[47,76],[51,79],[58,86],[62,91],[67,96]],
      "speaker": "Griffin",
      "avatar": "https://pub-75f38a18d7494e158433fd71f020ea01.r2.dev/mascot/griffin/face-happy.42579a9d4a.png?v=42579a9d4ac0",
      "side": "left",
      "tone": "accent"
    },
    {
      "n": 5,
      "durationInFrames": 154,
      "speechFrames": 124,
      "text": "Giọng đọc được thu trước, rồi mỗi cảnh được dựng đúng theo độ dài của giọng thật.",
      "ttsText": "Giọng đọc được thu trước, rồi mỗi cảnh được dựng đúng theo độ dài của giọng thật.",
      "words": [[0,0],[6,8],[10,14],[15,19],[19,25],[26,46],[30,53],[34,60],[39,66],[44,74],[49,79],[54,86],[59,91],[62,96],[66,104],[70,109],[76,116]],
      "speaker": "Griffin",
      "avatar": "https://pub-75f38a18d7494e158433fd71f020ea01.r2.dev/mascot/griffin/face-happy.42579a9d4a.png?v=42579a9d4ac0",
      "side": "left",
      "tone": "accent"
    },
    {
      "n": 6,
      "durationInFrames": 181,
      "speechFrames": 151,
      "text": "Cuối cùng, Studio ghép hình, giọng và nhạc nền thành một tệp video.",
      "ttsText": "Cuối cùng, xờ-tiu-đi-ô ghép hình, giọng và nhạc nền thành một tệp video.",
      "words": [[0,0],[5,6],[11,24],[23,52],[28,58],[34,74],[40,81],[43,85],[48,90],[52,98],[58,103],[62,108],[66,115]],
      "speaker": "Griffin",
      "avatar": "https://pub-75f38a18d7494e158433fd71f020ea01.r2.dev/mascot/griffin/face-happy.42579a9d4a.png?v=42579a9d4ac0",
      "side": "left",
      "tone": "accent"
    },
    {
      "n": 7,
      "durationInFrames": 187,
      "speechFrames": 157,
      "text": "Xong mỗi bước, bạn duyệt rồi mới đi tiếp, nên không có gì chạy ngoài ý muốn.",
      "ttsText": "Xong mỗi bước, bạn duyệt rồi mới đi tiếp, nên không có gì chạy ngoài ý muốn.",
      "words": [[0,0],[5,9],[9,16],[15,36],[19,44],[25,53],[29,57],[33,61],[36,68],[42,87],[46,94],[52,101],[55,106],[58,111],[63,117],[69,125],[71,130]],
      "speaker": "Griffin",
      "avatar": "https://pub-75f38a18d7494e158433fd71f020ea01.r2.dev/mascot/griffin/face-happy.42579a9d4a.png?v=42579a9d4ac0",
      "side": "left",
      "tone": "accent"
    },
    {
      "n": 8,
      "durationInFrames": 79,
      "speechFrames": 49,
      "text": "Giờ thì đến lượt bạn thử rồi đó!",
      "ttsText": "Giờ thì đến lượt bạn thử rồi đó!",
      "words": [[0,0],[4,7],[8,11],[12,16],[17,22],[21,27],[25,33],[29,38]],
      "speaker": "Griffin",
      "avatar": "https://pub-75f38a18d7494e158433fd71f020ea01.r2.dev/mascot/griffin/face-happy.42579a9d4a.png?v=42579a9d4ac0",
      "side": "left",
      "tone": "accent"
    }
  ]
};
