// Generated by tools/griffin-assets.py from tools/griffin-assets.json — do not edit by hand.
// Each pose picture is assets/mascot/griffin/<pose>-<mood>.png, 820 px tall (crest on the top edge,
// feet on the bottom edge). w = its width · hx = head centre as a share of it · moods = the ones drawn,
// the first being the default when a scene asks for one the pose does not have · walk = steps on its own.
// Props: w/h = picture size · k = size against the other props.
export const PIC_H = 820;

export const MOOD_LABELS = {
  neutral: "Bình thường",
  happy: "Vui",
  wink: "Nháy mắt",
  surprised: "Ngạc nhiên",
  thinking: "Suy nghĩ",
  sad: "Buồn",
  stern: "Nghiêm",
};

export const POSES = {
  stand: {"label": "Đứng", "group": "Tư thế", "w": 548, "hx": 0.59, "moods": ["neutral", "happy", "wink", "surprised", "thinking", "sad", "stern"]},
  sit: {"label": "Ngồi", "group": "Tư thế", "w": 647, "hx": 0.4, "moods": ["neutral", "happy", "wink", "surprised", "thinking", "sad", "stern"]},
  wings: {"label": "Giơ cánh", "group": "Tư thế", "w": 711, "hx": 0.52, "moods": ["neutral", "happy", "wink", "surprised", "thinking", "sad", "stern"]},
  turn: {"label": "Ba phần tư", "group": "Tư thế", "w": 822, "hx": 0.38, "moods": ["neutral", "happy", "wink", "surprised", "thinking", "sad", "stern"]},
  cheer: {"label": "Reo vui", "group": "Động tác", "w": 725, "hx": 0.5, "moods": ["neutral"]},
  welcome: {"label": "Chào đón", "group": "Động tác", "w": 766, "hx": 0.5, "moods": ["neutral"]},
  wave: {"label": "Vẫy cánh", "group": "Động tác", "w": 610, "hx": 0.46, "moods": ["neutral"]},
  rest: {"label": "Ngồi nghỉ", "group": "Động tác", "w": 550, "hx": 0.42, "moods": ["neutral"]},
  "walk-left": {"label": "Đi sang trái", "group": "Động tác", "w": 798, "hx": 0.35, "moods": ["neutral"], "walk": true},
  "walk-right": {"label": "Đi sang phải", "group": "Động tác", "w": 778, "hx": 0.62, "moods": ["neutral"], "walk": true},
};

export const PROPS = {
  lightbulb: {"label": "Bóng đèn", "file": "lightbulb", "w": 51, "h": 77},
  question: {"label": "Dấu hỏi", "file": "question_mark", "w": 52, "h": 86, "k": 1.3},
  exclamation: {"label": "Dấu chấm than", "file": "exclamation", "w": 29, "h": 85, "k": 1.3},
  sparkle: {"label": "Lấp lánh", "file": "sparkle", "w": 66, "h": 76},
};
