// Generated by tools/griffin-assets.py from tools/griffin-assets.json — do not edit by hand.
// Each picture is assets/mascot/griffin/<pose>-<mood>.png, 820 px tall (crest on the top edge, feet on the
// bottom edge). w = its width · hx = head centre as a share of it · moods = the ones drawn, the first
// being the default when a scene asks for one the pose does not have · walk = steps on its own.
export const PIC_H = 820;

export const POSES = {
  stand: {"w": 548, "hx": 0.59, "moods": ["neutral", "happy", "wink", "surprised", "thinking", "sad", "stern"]},
  sit: {"w": 647, "hx": 0.4, "moods": ["neutral", "happy", "wink", "surprised", "thinking", "sad", "stern"]},
  wings: {"w": 711, "hx": 0.52, "moods": ["neutral", "happy", "wink", "surprised", "thinking", "sad", "stern"]},
  turn: {"w": 822, "hx": 0.38, "moods": ["neutral", "happy", "wink", "surprised", "thinking", "sad", "stern"]},
  cheer: {"w": 725, "hx": 0.5, "moods": ["neutral"]},
  welcome: {"w": 766, "hx": 0.5, "moods": ["neutral"]},
  wave: {"w": 610, "hx": 0.46, "moods": ["neutral"]},
  rest: {"w": 550, "hx": 0.42, "moods": ["neutral"]},
  "walk-left": {"w": 798, "hx": 0.35, "moods": ["neutral"], "walk": true},
  "walk-right": {"w": 778, "hx": 0.62, "moods": ["neutral"], "walk": true},
};
