// Generated by tools/griffin-assets.py from tools/griffin-assets.json — do not edit by hand.
// Each pose picture is assets/mascot/griffin/<pose>-<mood>.png, 820 px tall (crest on the top edge,
// feet on the bottom edge). w = its width · hx = head centre as a share of it · moods = the ones drawn,
// the first being the default when a scene asks for one the pose does not have · walk = steps on its own.
// Props: w/h = picture size · k = size against the other props.
// The pictures live on the media store (R2): BASE + FILES[name], names carrying a content fingerprint.
export const PIC_H = 820;

export const BASE = "https://pub-75f38a18d7494e158433fd71f020ea01.r2.dev/mascot/griffin/";

export const MOOD_LABELS = {
  neutral: "Bình thường",
  happy: "Vui",
  wink: "Nháy mắt",
  surprised: "Ngạc nhiên",
  thinking: "Suy nghĩ",
  sad: "Buồn",
  stern: "Nghiêm",
};

export const POSES = {
  stand: {"label": "Đứng", "group": "Tư thế", "w": 548, "hx": 0.59, "moods": ["neutral", "happy", "wink", "surprised", "thinking", "sad", "stern"]},
  wings: {"label": "Giơ cánh", "group": "Tư thế", "w": 711, "hx": 0.52, "moods": ["neutral", "happy", "wink", "surprised", "thinking", "sad", "stern"]},
  "walk-left": {"label": "Đi sang trái", "group": "Tư thế", "w": 822, "hx": 0.38, "moods": ["neutral", "happy", "wink", "surprised", "thinking", "sad", "stern"], "walk": true},
  "walk-right": {"label": "Đi sang phải", "group": "Tư thế", "w": 822, "hx": 0.62, "moods": ["neutral", "happy", "wink", "surprised", "thinking", "sad", "stern"], "walk": true},
  welcome: {"label": "Chào đón", "group": "Động tác", "w": 766, "hx": 0.5, "moods": ["neutral"]},
  wave: {"label": "Vẫy cánh", "group": "Động tác", "w": 610, "hx": 0.46, "moods": ["neutral"]},
  rest: {"label": "Ngồi nghỉ", "group": "Động tác", "w": 550, "hx": 0.42, "moods": ["neutral"]},
};

export const PROPS = {
  lightbulb: {"label": "Bóng đèn", "file": "lightbulb", "w": 51, "h": 77},
  question: {"label": "Dấu hỏi", "file": "question_mark", "w": 52, "h": 86, "k": 1.3},
  exclamation: {"label": "Dấu chấm than", "file": "exclamation", "w": 29, "h": 85, "k": 1.3},
  sparkle: {"label": "Lấp lánh", "file": "sparkle", "w": 66, "h": 76},
};

export const FILES = {
  "badge-happy": "badge-happy.24026978ad.png",
  "badge-neutral": "badge-neutral.d199735f3a.png",
  "badge-sad": "badge-sad.2a0a1bebba.png",
  "badge-stern": "badge-stern.d49aacf93f.png",
  "badge-surprised": "badge-surprised.6ad7016bd2.png",
  "badge-thinking": "badge-thinking.da6a681183.png",
  "badge-wink": "badge-wink.0b1c47de7b.png",
  exclamation: "exclamation.9c66e3c52b.png",
  "face-happy": "face-happy.42579a9d4a.png",
  "face-neutral": "face-neutral.7b56828b41.png",
  "face-sad": "face-sad.73873d36f1.png",
  "face-stern": "face-stern.f3b545f647.png",
  "face-surprised": "face-surprised.6242605264.png",
  "face-thinking": "face-thinking.61f7a5c5e6.png",
  "face-wink": "face-wink.c30f6f34da.png",
  lightbulb: "lightbulb.8c7722f0f2.png",
  question_mark: "question_mark.161c7e76c3.png",
  "rest-neutral": "rest-neutral.166d7a43a5.png",
  sparkle: "sparkle.b789caf031.png",
  "stand-happy": "stand-happy.a1405eabd6.png",
  "stand-neutral": "stand-neutral.049e971db1.png",
  "stand-sad": "stand-sad.83e45e32ab.png",
  "stand-stern": "stand-stern.147bcb1bfe.png",
  "stand-surprised": "stand-surprised.4fb68e9601.png",
  "stand-thinking": "stand-thinking.21286ba5b6.png",
  "stand-wink": "stand-wink.77d4f31631.png",
  "walk-left-happy": "walk-left-happy.a499063126.png",
  "walk-left-neutral": "walk-left-neutral.629654a49f.png",
  "walk-left-sad": "walk-left-sad.ad52bb9302.png",
  "walk-left-stern": "walk-left-stern.428a7bda9b.png",
  "walk-left-surprised": "walk-left-surprised.64be38880d.png",
  "walk-left-thinking": "walk-left-thinking.d76619b517.png",
  "walk-left-wink": "walk-left-wink.aa8b95f8a4.png",
  "walk-right-happy": "walk-right-happy.587566f627.png",
  "walk-right-neutral": "walk-right-neutral.b860daa07f.png",
  "walk-right-sad": "walk-right-sad.488bf1be8e.png",
  "walk-right-stern": "walk-right-stern.438f2296ad.png",
  "walk-right-surprised": "walk-right-surprised.17efb0d562.png",
  "walk-right-thinking": "walk-right-thinking.d7675133df.png",
  "walk-right-wink": "walk-right-wink.ff3dfda383.png",
  "wave-neutral": "wave-neutral.be66de6352.png",
  "welcome-neutral": "welcome-neutral.b06105aa9b.png",
  "wings-happy": "wings-happy.00c239634b.png",
  "wings-neutral": "wings-neutral.10e7412810.png",
  "wings-sad": "wings-sad.c0e69b871d.png",
  "wings-stern": "wings-stern.05bef47d98.png",
  "wings-surprised": "wings-surprised.4a7a2a7084.png",
  "wings-thinking": "wings-thinking.a52ed9749b.png",
  "wings-wink": "wings-wink.2b9188a7e9.png",
};
