#!/usr/bin/env node
/**
 * Build the VinUni Lesson Video design-system bundle.
 *
 *   node tools/build.mjs          → vinuni-lesson-video-ds/dist/vk.js  (window.VK, React bundled)
 *                                 → vinuni-lesson-video-ds/assets/icons/*.svg
 *
 * Needs esbuild + react + react-dom. Lookup order: $VK_NODE_MODULES, tools/node_modules,
 * ./node_modules, then the Video-studio repo (../Coding/Video-studio/node_modules) — used
 * read-only. Standalone: `cd tools && npm i esbuild react react-dom`.
 */
import fs from 'node:fs';
import fsp from 'node:fs/promises';
import { createRequire } from 'node:module';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, '..');
// Which design system to build: the stable one by default, or VK_DS=vinuni-lesson-video-ds-lab.
const DS = path.resolve(ROOT, process.env.VK_DS || 'vinuni-lesson-video-ds');
if (!fs.existsSync(path.join(DS, 'lib/index.js'))) {
  console.error(`No design system at ${DS}`);
  process.exit(1);
}
const SCENES_DIR = path.join(DS, 'ui_kits/lesson-video/scenes');
const VIDEOS_DIR = path.join(DS, 'ui_kits/lesson-video/videos');

const candidates = [
  process.env.VK_NODE_MODULES,
  path.join(HERE, 'node_modules'),
  path.join(ROOT, 'node_modules'),
  path.resolve(ROOT, '../Coding/Video-studio/node_modules'),
].filter(Boolean);
const NODE_MODULES = candidates.find((p) => fs.existsSync(path.join(p, 'esbuild')) && fs.existsSync(path.join(p, 'react-dom')));
if (!NODE_MODULES) {
  console.error('Cannot find esbuild + react-dom. Run `npm i esbuild react react-dom` in tools/ or set VK_NODE_MODULES.');
  process.exit(1);
}
const require = createRequire(path.join(NODE_MODULES, 'noop.js'));
const esbuild = require('esbuild');

/** Virtual module "vk:scenes": every ui_kits/lesson-video/scenes/*.jsx, sorted by file name. */
const scenesPlugin = {
  name: 'vk-scenes',
  setup(build) {
    build.onResolve({ filter: /^vk:scenes$/ }, () => ({ path: 'vk:scenes', namespace: 'vk-scenes' }));
    build.onLoad({ filter: /.*/, namespace: 'vk-scenes' }, async () => {
      const files = (await fsp.readdir(SCENES_DIR)).filter((f) => f.endsWith('.jsx')).sort();
      const imports = files.map((f, i) => `import S${i}, { meta as M${i} } from ${JSON.stringify(path.join(SCENES_DIR, f))};`);
      const list = files.map((f, i) => `  { ...M${i}, component: S${i}, file: ${JSON.stringify(f)} }`);
      return {
        contents: `${imports.join('\n')}\nexport const scenes = [\n${list.join(',\n')}\n];\n`,
        resolveDir: SCENES_DIR,
        loader: 'js',
      };
    });
    // "vk:videos": every ui_kits/lesson-video/videos/<name>/video.jsx (complete example videos).
    build.onResolve({ filter: /^vk:videos$/ }, () => ({ path: 'vk:videos', namespace: 'vk-videos' }));
    build.onLoad({ filter: /.*/, namespace: 'vk-videos' }, async () => {
      const dirs = fs.existsSync(VIDEOS_DIR)
        ? (await fsp.readdir(VIDEOS_DIR, { withFileTypes: true }))
            .filter((d) => d.isDirectory() && fs.existsSync(path.join(VIDEOS_DIR, d.name, 'video.jsx')))
            .map((d) => d.name)
            .sort()
        : [];
      const imports = dirs.map((d, i) => `import V${i}, { meta as W${i} } from ${JSON.stringify(path.join(VIDEOS_DIR, d, 'video.jsx'))};`);
      const list = dirs.map((d, i) => `  { ...W${i}, component: V${i}, kind: 'video', dir: ${JSON.stringify(d)} }`);
      return {
        contents: `${imports.join('\n')}\nexport const videos = [\n${list.join(',\n')}\n];\n`,
        resolveDir: fs.existsSync(VIDEOS_DIR) ? VIDEOS_DIR : DS,
        loader: 'js',
      };
    });
  },
};

/** The entry files import '../vinuni-lesson-video-ds/…'; point those imports at the selected DS. */
const dsPlugin = {
  name: 'vk-ds',
  setup(build) {
    build.onResolve({ filter: /^\.\.\/vinuni-lesson-video-ds\// }, (a) => ({
      path: path.join(DS, a.path.slice('../vinuni-lesson-video-ds/'.length)),
    }));
  },
};

const common = {
  bundle: true,
  jsx: 'automatic',
  nodePaths: [NODE_MODULES],
  loader: { '.js': 'jsx', '.jsx': 'jsx' },
  define: { 'process.env.NODE_ENV': '"production"' },
  logLevel: 'warning',
};

const t0 = Date.now();
await esbuild.build({
  ...common,
  entryPoints: [path.join(HERE, 'vk.entry.js')],
  outfile: path.join(DS, 'dist/vk.js'),
  format: 'iife',
  globalName: 'VK',
  platform: 'browser',
  target: ['es2020'],
  minify: true,
  legalComments: 'eof',
  plugins: [dsPlugin, scenesPlugin],
  banner: {
    js: '/* VinUni Lesson Video Kit — generated by tools/build.mjs from lib/, components/ and ui_kits/. Do not edit by hand. */',
  },
});

const icons = await esbuild.build({
  ...common,
  entryPoints: [path.join(HERE, 'icons.entry.js')],
  write: false,
  format: 'cjs',
  platform: 'node',
  plugins: [dsPlugin],
});
const mod = { exports: {} };
new Function('module', 'exports', 'require', icons.outputFiles[0].text)(mod, mod.exports, require);
const rendered = mod.exports.renderIcons();
await fsp.mkdir(path.join(DS, 'assets/icons'), { recursive: true });
for (const [name, markup] of Object.entries(rendered)) {
  await fsp.writeFile(path.join(DS, 'assets/icons', `${name}.svg`), `${markup}\n`);
}

const size = fs.statSync(path.join(DS, 'dist/vk.js')).size;
const sceneCount = (await fsp.readdir(SCENES_DIR)).filter((f) => f.endsWith('.jsx')).length;
console.log(`dist/vk.js ${(size / 1024).toFixed(1)} KiB · ${sceneCount} scenes · ${Object.keys(rendered).length} icons · ${Date.now() - t0} ms`);
