#!/usr/bin/env node
/**
 * Measure the whiteboard handwriting fonts and write components/whiteboard/handFonts.js (generated).
 *
 *   node tools/hand-fonts.mjs
 *
 * The board reveals text left to right and moves the marker along it without a DOM, so it needs every
 * glyph's advance width up front. This loads each font file from vinuni-lesson-video-ds/fonts/ into headless
 * Chromium (as a data: URL — no server), measures ASCII + every precomposed Vietnamese letter at the font's
 * board weight, and writes the table. Add a font = add a line to FONTS (+ its @font-face in
 * tokens/colors_and_type.css), run this, commit both.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { chromium } from 'playwright';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const DS = path.join(ROOT, 'vinuni-lesson-video-ds');
const OUT = path.join(DS, 'components/whiteboard/handFonts.js');

// key → CSS family, file in fonts/, weight the board writes in, label for docs / Studio
const FONTS = [
  { key: 'playpen', family: 'Playpen Sans', file: 'PlaypenSans-VariableFont_wght.ttf', weight: 500, label: 'Playpen Sans' },
  { key: 'shantell', family: 'Shantell Sans', file: 'ShantellSans-VariableFont.ttf', weight: 600, label: 'Shantell Sans' },
  { key: 'pangolin', family: 'Pangolin', file: 'Pangolin-Regular.ttf', weight: 400, label: 'Pangolin' },
];
const DEFAULT = 'playpen';

const vi = 'àáảãạăằắẳẵặâầấẩẫậèéẻẽẹêềếểễệìíỉĩịòóỏõọôồốổỗộơờớởỡợùúủũụưừứửữựỳýỷỹỵđ';
let chars = '';
for (let i = 32; i < 127; i++) chars += String.fromCharCode(i);
chars += vi + vi.toUpperCase() + '…–—“”‘’·→•';

const faces = FONTS.map((f) => {
  const b64 = fs.readFileSync(path.join(DS, 'fonts', f.file)).toString('base64');
  return `@font-face{font-family:"${f.family}";src:url(data:font/ttf;base64,${b64});font-weight:100 900}`;
}).join('\n');

const browser = await chromium.launch();
const page = await browser.newPage();
await page.setContent(`<html><head><meta charset="utf-8"><style>${faces}</style></head><body></body></html>`);
const table = await page.evaluate(async ({ fonts, chars }) => {
  const c = document.createElement('canvas').getContext('2d');
  const out = {};
  for (const f of fonts) {
    await document.fonts.load(`${f.weight} 100px "${f.family}"`);
    if (!document.fonts.check(`${f.weight} 100px "${f.family}"`)) throw new Error(`font ${f.family} did not load`);
    c.font = `${f.weight} 1000px "${f.family}"`;
    const adv = {};
    for (const ch of chars) adv[ch] = Math.round(c.measureText(ch).width);
    out[f.key] = adv;
  }
  return out;
}, { fonts: FONTS, chars });
await browser.close();

const body = FONTS.map((f) => {
  const adv = Object.entries(table[f.key]).map(([ch, w]) => `${JSON.stringify(ch)}: ${w}`).join(', ');
  return `  ${f.key}: {\n    family: ${JSON.stringify(f.family)},\n    label: ${JSON.stringify(f.label)},\n    weight: ${f.weight},\n    advance: { ${adv} },\n  },`;
}).join('\n');
fs.writeFileSync(
  OUT,
  `// Generated by tools/hand-fonts.mjs — do not edit by hand.
/**
 * The whiteboard's handwriting fonts (fonts/, SIL OFL 1.1): CSS family, the weight the board writes in, and
 * each glyph's advance width per 1000 units of font size, measured in Chromium. Text marks pick one with
 * \`font: '<key>'\`; the board's default is HAND_DEFAULT.
 */
export const HAND_DEFAULT = ${JSON.stringify(DEFAULT)};

export const HAND_FONTS = {
${body}
};
`,
);
console.log(`✓ ${path.relative(ROOT, OUT)} · ${FONTS.map((f) => `${f.key} (${f.family} ${f.weight})`).join(' · ')} · ${chars.length} glyphs`);
