#!/usr/bin/env node
/**
 * Bind a recorded narration to a design-system video: voice.cues.json (from tts-elevenlabs or any
 * generator with the same shape) → <video dir>/voice.js, which timeline.js reads to retime every scene.
 *
 *   node tools/voice-timing.mjs <voice.cues.json> <ui_kits/lesson-video/videos/<name>>
 *   node tools/voice-timing.mjs --clear <video dir>          back to the authored (script-estimate) timing
 *
 * Fails if the narration text of any cue differs from cues.js (the recording would be stale).
 */
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';

const [a, b] = process.argv.slice(2);
const fail = (m) => {
  console.error(`✗ ${m}`);
  process.exit(1);
};
const HEADER = '// Generated by tools/voice-timing.mjs — do not edit by hand.\n';

if (a === '--clear') {
  if (!b) fail('usage: --clear <video dir>');
  fs.writeFileSync(path.join(b, 'voice.js'), `${HEADER}// No narration bound: scenes play at their authored (script-estimate) durations.\nexport const VOICE = null;\n`);
  console.log(`✓ ${path.join(b, 'voice.js')} cleared`);
  process.exit(0);
}
if (!a || !b) fail('usage: node tools/voice-timing.mjs <voice.cues.json> <video dir>');

const manifest = JSON.parse(fs.readFileSync(a, 'utf8'));
const cuesSrc = fs.readFileSync(path.join(b, 'cues.js'), 'utf8');
const { CUES } = await import(`data:text/javascript;base64,${Buffer.from(cuesSrc).toString('base64')}`);
if (manifest.fps !== 30) fail(`manifest fps ${manifest.fps} ≠ 30`);
if (manifest.cues.length !== CUES.length) fail(`manifest has ${manifest.cues.length} cues, cues.js has ${CUES.length}`);
manifest.cues.forEach((m, i) => {
  if (m.n !== CUES[i].n) fail(`cue order differs at index ${i}: ${m.n} vs ${CUES[i].n}`);
  if (m.text !== CUES[i].text.trim()) fail(`câu ${m.n}: recorded text differs from cues.js — re-record it`);
});
const wavPath = path.join(path.dirname(path.resolve(a)), 'voice.wav');
const voice = {
  generator: manifest.generator,
  model: manifest.model ?? null,
  source: path.resolve(a),
  audioSha256: fs.existsSync(wavPath) ? crypto.createHash('sha256').update(fs.readFileSync(wavPath)).digest('hex') : null,
  durationInFrames: manifest.durationInFrames,
  cues: manifest.cues.map((m) => ({ n: m.n, durationInFrames: m.durationInFrames, speechFrames: m.speechFrames, text: m.text })),
};
fs.writeFileSync(path.join(b, 'voice.js'), `${HEADER}export const VOICE = ${JSON.stringify(voice, null, 2)};\n`);
const authored = CUES.reduce((s, c) => s + (c.end - c.start), 0);
console.log(`✓ ${path.join(b, 'voice.js')} · ${voice.durationInFrames} f (${(voice.durationInFrames / 30).toFixed(2)} s) · authored ${authored} f`);
console.log('  scale per câu: ' + manifest.cues.map((m, i) => ((CUES[i].end - CUES[i].start) / m.durationInFrames).toFixed(2)).join(' '));
