// Generated by tools/voice-timing.mjs — do not edit by hand.
export const VOICE = {
  "generator": "elevenlabs",
  "model": "eleven_v3",
  "source": "tts-elevenlabs/out/d2-01-lab/voice.cues.json",
  "audioSha256": "abfc540cba10684da11a07d8e498c7f30b252d7b4cd63b26df341df39e85bcca",
  "durationInFrames": 9491,
  "cues": [
    {
      "n": 1,
      "durationInFrames": 209,
      "speechFrames": 167,
      "text": "Nếu đội hỗ trợ muốn làm phần mềm để học viên nhắn hỏi và nhận trả lời, bạn đã biết khó khăn cần giải quyết chưa?"
    },
    {
      "n": 2,
      "durationInFrames": 214,
      "speechFrames": 172,
      "text": "Phần mềm trò chuyện như vậy gọi là trợ lý hội thoại, nhưng tên gọi chưa cho biết học viên đang vướng điều gì."
    },
    {
      "n": 3,
      "durationInFrames": 213,
      "speechFrames": 171,
      "text": "Mình sẽ theo tình huống minh họa Lan tìm hướng dẫn nộp bài, bắt đầu từ khó khăn rồi mới chọn cách giải quyết."
    },
    {
      "n": 4,
      "durationInFrames": 209,
      "speechFrames": 167,
      "text": "Lan là học viên mới, sắp nộp bài lần đầu, nhưng hướng dẫn nằm rải rác trên nhiều trang của khóa học."
    },
    {
      "n": 5,
      "durationInFrames": 247,
      "speechFrames": 205,
      "text": "Dũng là nhân viên hỗ trợ phải trả lời những câu hỏi lặp lại, như gửi đường dẫn rồi hỏi Lan học lớp nào."
    },
    {
      "n": 6,
      "durationInFrames": 228,
      "speechFrames": 168,
      "text": "Cuối video, bạn sẽ viết một câu nêu rõ khó khăn và chọn cách đo xem khó khăn ấy có giảm không."
    },
    {
      "n": 7,
      "durationInFrames": 153,
      "speechFrames": 111,
      "text": "Công việc Lan muốn hoàn thành là gửi đúng bài vào đúng nơi trước thời hạn."
    },
    {
      "n": 8,
      "durationInFrames": 146,
      "speechFrames": 104,
      "text": "Trò chuyện với máy chỉ có ích nếu giúp Lan hoàn thành công việc ấy."
    },
    {
      "n": 9,
      "durationInFrames": 155,
      "speechFrames": 113,
      "text": "Trở ngại hiện tại là Lan chưa xác định được hướng dẫn nào áp dụng cho lớp của mình."
    },
    {
      "n": 10,
      "durationInFrames": 236,
      "speechFrames": 194,
      "text": "Đề nghị làm trợ lý hội thoại đã nói đến cách giải quyết, trong khi nhóm còn cần xác nhận vì sao Lan gặp khó khăn."
    },
    {
      "n": 11,
      "durationInFrames": 189,
      "speechFrames": 147,
      "text": "Nếu chỉ lo xây phần mềm trò chuyện, nhóm có thể bỏ qua chỗ khiến Lan không tìm được đúng hướng dẫn."
    },
    {
      "n": 12,
      "durationInFrames": 198,
      "speechFrames": 156,
      "text": "Trợ lý hội thoại trả lời nhanh nhưng gửi nhầm hướng dẫn thì Lan vẫn chưa nhận được kết quả cần thiết."
    },
    {
      "n": 13,
      "durationInFrames": 196,
      "speechFrames": 154,
      "text": "Một nút hướng dẫn đặt đúng chỗ cũng có thể giúp Lan, dù phương án này không dùng trí tuệ nhân tạo."
    },
    {
      "n": 14,
      "durationInFrames": 236,
      "speechFrames": 176,
      "text": "Vì vậy, mình viết rõ Lan vướng điều gì trước, còn cách giải quyết sẽ chọn sau khi đã hiểu khó khăn đó."
    },
    {
      "n": 15,
      "durationInFrames": 188,
      "speechFrames": 146,
      "text": "Trước tiên là ai gặp khó khăn, vì học viên mới có thể vướng những chỗ mà học viên cũ không gặp."
    },
    {
      "n": 16,
      "durationInFrames": 195,
      "speechFrames": 153,
      "text": "Tiếp theo, mình xác định Lan vướng ở bước tìm hướng dẫn, chọn nơi nộp hay tải tệp."
    },
    {
      "n": 17,
      "durationInFrames": 204,
      "speechFrames": 162,
      "text": "Mình cũng hỏi những học viên khác có thường gặp khó khăn này không, vì một trường hợp chưa nói lên tình hình cả lớp."
    },
    {
      "n": 18,
      "durationInFrames": 242,
      "speechFrames": 200,
      "text": "Sau đó, mình tìm hậu quả cụ thể, như Lan phải chờ lâu, nộp nhầm nơi, hoặc Dũng phải trả lời lại."
    },
    {
      "n": 19,
      "durationInFrames": 198,
      "speechFrames": 156,
      "text": "Nhóm xem học viên tự tìm hướng dẫn và ghi chỗ họ dừng lại, rồi đối chiếu với điều họ kể."
    },
    {
      "n": 20,
      "durationInFrames": 196,
      "speechFrames": 154,
      "text": "Khi trao đổi, mình hỏi Lan đã tìm hướng dẫn ở đâu trước tiên, để biết điều thực sự xảy ra."
    },
    {
      "n": 21,
      "durationInFrames": 233,
      "speechFrames": 191,
      "text": "Các yêu cầu hỗ trợ đã lưu giúp mình thấy câu hỏi nào lặp lại, nhưng cần đọc kỹ và hỏi thêm để hiểu lý do."
    },
    {
      "n": 22,
      "durationInFrames": 200,
      "speechFrames": 158,
      "text": "Nếu số học viên tăng, số câu hỏi cũng có thể tăng dù mỗi người không gặp khó khăn nhiều hơn."
    },
    {
      "n": 23,
      "durationInFrames": 193,
      "speechFrames": 133,
      "text": "Những ghi chép trên màn hình minh họa cách tìm bằng chứng, không phải kết quả khảo sát thật."
    },
    {
      "n": 24,
      "durationInFrames": 201,
      "speechFrames": 159,
      "text": "Yêu cầu ban đầu chỉ nói làm trợ lý hội thoại hỗ trợ học viên, nên mình cần viết lại cho rõ khó khăn."
    },
    {
      "n": 25,
      "durationInFrames": 155,
      "speechFrames": 113,
      "text": "Mình bắt đầu bằng người đang gặp khó khăn, ở đây là học viên mới trong khóa học."
    },
    {
      "n": 26,
      "durationInFrames": 158,
      "speechFrames": 116,
      "text": "Tiếp theo, mình nêu họ khó tìm đúng hướng dẫn khi chuẩn bị nộp bài lần đầu."
    },
    {
      "n": 27,
      "durationInFrames": 136,
      "speechFrames": 94,
      "text": "Cuối cùng là hậu quả phải chờ hỗ trợ và hỏi lại nhiều lần."
    },
    {
      "n": 28,
      "durationInFrames": 206,
      "speechFrames": 164,
      "text": "Học viên mới khó tìm đúng hướng dẫn cho lớp mình trước lần nộp bài đầu tiên, nên phải chờ hỗ trợ và hỏi lại."
    },
    {
      "n": 29,
      "durationInFrames": 216,
      "speechFrames": 174,
      "text": "Câu vừa viết giúp nhóm hiểu cần giải quyết việc gì, còn trợ lý hội thoại có giúp được hay không vẫn phải thử."
    },
    {
      "n": 30,
      "durationInFrames": 198,
      "speechFrames": 156,
      "text": "Mình chọn theo dõi thời gian tìm đúng hướng dẫn, gọi là một chỉ số để kiểm tra việc này có nhanh hơn không."
    },
    {
      "n": 31,
      "durationInFrames": 202,
      "speechFrames": 160,
      "text": "Trong phiếu minh họa, Lan bắt đầu lúc bảy giờ tối và tìm đúng hướng dẫn của lớp sau đó tám phút."
    },
    {
      "n": 32,
      "durationInFrames": 196,
      "speechFrames": 154,
      "text": "Thời gian tìm trong ví dụ là tám phút, chứ không chỉ là thời gian Dũng gõ câu trả lời cuối cùng."
    },
    {
      "n": 33,
      "durationInFrames": 200,
      "speechFrames": 158,
      "text": "Mình ghi vị trí và nội dung hai lượt hỏi lại trên trục thời gian để tìm hiểu Lan vướng ở bước nào."
    },
    {
      "n": 34,
      "durationInFrames": 248,
      "speechFrames": 188,
      "text": "Khi thử cách mới, nhóm vẫn giao cùng việc tìm hướng dẫn và chỉ dừng đồng hồ khi tìm đúng hướng dẫn của lớp."
    },
    {
      "n": 35,
      "durationInFrames": 208,
      "speechFrames": 166,
      "text": "Nhóm cho rằng hướng dẫn khó tìm là nguyên nhân chính, nhưng đây mới là một giả định cần kiểm tra."
    },
    {
      "n": 36,
      "durationInFrames": 232,
      "speechFrames": 190,
      "text": "Nếu Lan đã thấy hướng dẫn nhưng không hiểu từ ngữ bên trong, việc đổi vị trí đường dẫn có thể chưa giúp nhiều."
    },
    {
      "n": 37,
      "durationInFrames": 226,
      "speechFrames": 184,
      "text": "Mình cần xem thêm để biết Lan thiếu đường dẫn, thiếu thông tin hay đã thấy hướng dẫn mà vẫn không hiểu."
    },
    {
      "n": 38,
      "durationInFrames": 216,
      "speechFrames": 174,
      "text": "Điều nhóm muốn đạt là Lan tìm đúng hướng dẫn dễ hơn, còn Dũng bớt phải trả lời những câu hỏi lặp lại."
    },
    {
      "n": 39,
      "durationInFrames": 246,
      "speechFrames": 204,
      "text": "Số câu trả lời máy tạo ra chưa chứng minh khó khăn đã giảm, vì Lan có thể phải hỏi nhiều lần mới nhận được hướng dẫn đúng."
    },
    {
      "n": 40,
      "durationInFrames": 235,
      "speechFrames": 175,
      "text": "Trước khi xây, hãy ghi cạnh nhau khó khăn cần giải quyết, con số sẽ đo và điều nhóm còn chưa xác nhận."
    },
    {
      "n": 41,
      "durationInFrames": 203,
      "speechFrames": 185,
      "text": "Đề nghị làm một trợ lý được tự chọn cách xử lý rồi gửi thư điện tử còn thiếu thông tin gì để quyết định có nên xây?"
    },
    {
      "n": 42,
      "durationInFrames": 150,
      "speechFrames": 0,
      "text": ""
    },
    {
      "n": 43,
      "durationInFrames": 210,
      "speechFrames": 168,
      "text": "Mình cần biết ai gặp vấn đề, khó khăn ở bước nào và có bằng chứng gì cho thấy khó khăn ấy đang xảy ra."
    },
    {
      "n": 44,
      "durationInFrames": 164,
      "speechFrames": 122,
      "text": "Mình cũng cần biết kết quả mong muốn và hậu quả của việc gửi thư điện tử sai."
    },
    {
      "n": 45,
      "durationInFrames": 192,
      "speechFrames": 150,
      "text": "Tên giải pháp chưa cho biết những điều đó, nên nhóm chưa đủ cơ sở quyết định có nên xây hệ thống ấy."
    },
    {
      "n": 46,
      "durationInFrames": 215,
      "speechFrames": 173,
      "text": "Bạn hãy viết lại yêu cầu ấy thành một câu nêu rõ khó khăn và chọn một con số để theo dõi kết quả."
    },
    {
      "n": 47,
      "durationInFrames": 200,
      "speechFrames": 140,
      "text": "Từ câu vấn đề và cách kiểm tra, mình sẽ tìm các hướng giải quyết ở video sau."
    }
  ]
};
